import anthropic
from datetime import date


SYSTEM_PROMPT = """You are an expert semiconductor industry analyst writing a concise daily briefing.
Your audience is technically literate professionals who want signal, not noise.

ABSOLUTE OUTPUT RULE: Your response must begin with <!DOCTYPE html> — no exceptions.
Do not write any text, reasoning, commentary, or explanation before the HTML tag.
Do not narrate your search process. Do not say "I'll now search" or "Based on my research".
The first character of your response must be < and nothing else.

When generating the newsletter:
- Search for TODAY's semiconductor news across all coverage areas
- Be specific: include company names, numbers, and dates
- Keep each section tight — 3 to 5 bullet points maximum
- Flag anything that is a meaningful shift, not just routine updates
- CRITICAL: Always provide readthroughs showing how news impacts other companies or the broader market (e.g., "X company's announcement will affect Y companies' competitive position")
- Connect futures moves to macro drivers and semiconductor news
- Identify potential market mispricings based on the day's developments
"""

USER_PROMPT = f"""Today is {date.today().strftime("%B %d, %Y")}.

PRIMARY SOURCES: Focus your search on Trendforce, ZDnet, EE Times, SemiAnalysis, and Digitimes for Sections 1 (Semiconductor Industry News) and 3 (Technology & Process Nodes). For Section 2 (Geopolitics & Trade), prioritize general media outlets.
Search the web for the latest semiconductor industry news from the past 24 hours and generate a daily briefing email in HTML format.

START WITH:
- S&P 500 futures opening level and direction (e.g., "S&P 500 futures opening +50 bps" or "-50 bps")
- Nasdaq futures opening level and direction (e.g., "Nasdaq futures opening +75 bps" or "-30 bps")
- The key macro driver for these moves (e.g., "Trump said Strait of Hormuz will open..." or relevant geopolitical/economic headline)

Cover these 3 areas:
1. Semiconductor Industry News & Market Impact
Search for overnight news only — stories published in the last 24 hours. Prioritize Trendforce, ZDnet, EE Times, SemiAnalysis, and Digitimes.
This is a daily newsletter; do not repeat macro themes or well-known background context that hasn't changed. Focus on what is new today.
STRICT: Every story must have been published within the last 24 hours. Before including any item,
verify its publication date. Discard anything older.
Cover these segments when relevant: model makers, semi-cap equipment, GPU/CPU/ASICs,
testers, OSATs, foundries, memory (include DRAM/NAND spot/contract price moves if reported today),
fabless houses, supply chain.
Select 3-5 stories maximum — only the most market-moving items. Skip anything routine or unchanged.
STRICT: For each story, lead with the market impact and cite the source in parentheses e.g. (SemiAnalysis), (Trendforce),
(Digitimes), (EE Times), (ZDnet). Only add a readthrough if there is a genuine cross-company
or supply chain implication — keep it to 2-3 sentences max. Do not force a readthrough where none exists.
2. Geopolitics & Trade — export controls, supply chain shifts, government subsidies, CHIPS Act updates 
STRICT: Cite the source in parentheses for every item e.g. (WSJ), (Reuters), (Bloomberg), (FT), (SCMP).
3. Technology & Process Nodes — new node announcements, chiplet architectures, packaging innovations, EDA tools
STRICT: Cite the source in parentheses for every item e.g. (EE Times), (SemiAnalysis), (Trendforce), (Digitimes), (AnandTech).

END WITH:
- Biggest Winners and Losers (stock movers since last night)
- A 2-sentence summary of what the market might be mispricing based on today's semiconductor news

Format the output as a clean HTML email with:
- A header with today's date and the title "Semiconductor Daily Briefing"
- Futures and macro context at the top
- One <section> per coverage area with a bold heading
- Bullet points (<ul><li>) for each story with clear impact readthroughs
- A brief 1-sentence "So What?" takeaway in italics after each section
- Winners/Losers section
- Mispricing summary section
- A minimal inline CSS style block for clean rendering in Gmail (max-width 680px, font-family sans-serif, muted colors)
- A small footer with the text "Generated by your Semis Newsletter Agent"

ABSOLUTE: Begin your response with <!DOCTYPE html> immediately. 
No text, no commentary, no search narration before the HTML. First character must be <.
"""


def generate_newsletter(api_key: str) -> str:
    """
    Calls Claude with web search enabled and returns the HTML newsletter string.
    Claude autonomously searches, synthesizes, and formats — single API call.
    """
    client = anthropic.Anthropic(api_key=api_key)

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=8096,  # max context length to allow for long HTML output after searches
        system=SYSTEM_PROMPT,
        tools=[
            {
                "type": "web_search_20250305",
                "name": "web_search",
                "max_uses": 8,  # up to 6 searches per run — covers all 4 sections
            }
        ],
        messages=[
            {"role": "user", "content": USER_PROMPT}
        ],
    )

    # Extract the final text block — Claude returns tool use blocks mid-stream,
    # then a final text block with the HTML once searches are done
    html_content = ""
    for block in response.content:
        if block.type == "text":
            html_content += block.text
            # Strip markdown code fences if model wraps output in ```html ... ```
    html_content = html_content.strip()
    if html_content.startswith("```html"):
        html_content = html_content[7:]
    if html_content.startswith("```"):
        html_content = html_content[3:]
    if html_content.endswith("```"):
        html_content = html_content[:-3]
    html_content = html_content.strip()

    # Strip any narration before the HTML starts
    first_angle = html_content.find("<")
    if first_angle > 0:
        html_content = html_content[first_angle:]

    if not html_content:
        raise RuntimeError("Claude returned no text content — check API response for errors")

    return html_content